version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 0
  ignore:
  - dependency-name: gatsby-transformer-remark
    versions:
    - 4.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: gatsby-cli
    versions:
    - 3.1.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: gatsby
    versions:
    - 2.32.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 2.10.0
  - dependency-name: gatsby-plugin-typography
    versions:
    - 2.11.0
