---
title: Jeffry In
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jjwainwright2@gmail.com
description: Jeffry.in are posts by me, Jeffry Wainwright
baseurl: ''
url: "https://jeffry.in"
imgix: "https://yowainwright.imgix.net"
imgSq: "?fit=crop&w=700&h=700&auto=format"
imgSqSm: "?fit=crop&w=300&h=300&auto=format"
imgLs: "?fit=crop&w=350&h=175&auto=format"
imgFull: "?fit=crop&w=1500&h=500&auto=format"
imgFullSm: "?fit=crop&w=500&h=167&auto=format"
twitter_username: yowainwright
github_username: yowainwright
instagram_username: yowainwright
codepen_username: yowainwright
tumblr_account: "https://ratherbe.in"
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  style: compressed
jekyll-minifier:
  exclude: ''
gems:
- json
- jekyll-sitemap
- jekyll-redirect-from
- github-pages
- jekyll-minifier
- jekyll-autoprefixer
- jemoji
exclude:
- CNAME
- README
- node_modulesn
- _data
- _drafts
- bower.json
- package.json
- LICENSE
- vendor
