import { writeFileSync } from "fs";
import { join } from "path";
import { generateMermaidCSS } from "../lib/components/mermaid/constants";

const outputPath = join(
  process.cwd(),
  "lib/client/styles/scss",
  "_mermaid.scss",
);
const css = generateMermaidCSS();

const header = `// Auto-generated mermaid styles
// Generated by scripts/generate-mermaid-styles.ts

`;

writeFileSync(outputPath, header + css);

console.log("✅ Generated mermaid styles at", outputPath);
