#!/usr/bin/env bun

import { writeFile } from "fs/promises";
import { join } from "path";
import { buildCalculatorStyles } from "../lib/components/content/expensive-ai/TokenCostCalculator/styles";

const STYLES_PATH = join(
  process.cwd(),
  "lib/client/styles/scss/_calculator.scss",
);

async function generateComponentStyles() {
  const calculatorCSS = buildCalculatorStyles();

  const scssContent = `// Auto-generated component styles
// Generated by scripts/generate-component-styles.ts

${calculatorCSS}
`;

  await writeFile(STYLES_PATH, scssContent);
}

generateComponentStyles().catch(console.error);
