#!/usr/bin/env bun

import { writeFile, readFile } from 'fs/promises';
import { join } from 'path';
import { fetchAllPricing } from './fetch-prices';
import type { ReasoningMultipliers } from './types';

const CONSTANTS_PATH = join(process.cwd(), 'components/ai-cost-charts/TokenCostCalculator/constants.ts');
const CACHE_PATH = join(process.cwd(), '.cache/ai-pricing.json');

const REASONING_MULTIPLIERS: ReasoningMultipliers = {
  'claude-opus-4.5': 2.8,
  'gpt-5': 2.2,
  'gemini-3-ultra': 2.0,
  'deepseek-r1': 3.5,
  'grok-4.1': 1.8
};

const MODEL_NAMES = {
  'claude-opus-4.5': 'Claude Opus 4.5',
  'gpt-5': 'GPT-5',
  'gemini-3-ultra': 'Gemini 3 Ultra',
  'deepseek-r1': 'DeepSeek R1',
  'grok-4.1': 'Grok 4.1'
};

function generateConstantsFile(pricingData: any): string {
  const timestamp = new Date().toISOString();

  return `// This file is auto-generated by scripts/update-ai-pricing
// Last updated: ${timestamp}

export const MODEL_PRICING = ${JSON.stringify(pricingData, null, 2)};

export const REASONING_MULTIPLIERS = ${JSON.stringify(REASONING_MULTIPLIERS, null, 2)};

export const MODEL_NAMES = ${JSON.stringify(MODEL_NAMES, null, 2)};

export const LAST_UPDATED = '${timestamp}';
`;
}

async function loadCachedPricing() {
  try {
    const cached = await readFile(CACHE_PATH, 'utf-8');
    return JSON.parse(cached);
  } catch {
    return null;
  }
}

async function saveCachedPricing(pricing: any) {
  try {
    await writeFile(CACHE_PATH, JSON.stringify(pricing, null, 2));
  } catch {
    // ignore
  }
}

async function main() {
  try {
    const pricing = await fetchAllPricing();

    if (Object.keys(pricing).length === 0) {
      const cached = await loadCachedPricing();
      if (cached) {
        await writeFile(CONSTANTS_PATH, generateConstantsFile(cached));
        process.exit(0);
      }
      process.exit(1);
    }

    await saveCachedPricing(pricing);
    await writeFile(CONSTANTS_PATH, generateConstantsFile(pricing));

  } catch (error) {
    const cached = await loadCachedPricing();
    if (cached) {
      await writeFile(CONSTANTS_PATH, generateConstantsFile(cached));
      process.exit(0);
    }
    process.exit(1);
  }
}

main();