name: jeffry.in ci 🥤
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Nub and Node
        uses: nubjs/setup-nub@v0
        with:
          nub-version: 0.7.5
      - run: nub install --frozen-lockfile --ignore-scripts
      - run: nub run lint
      - run: nub run build
        env:
          CI: true
