name: update deps

on:
  schedule:
    - cron: "0 5 * * 2"

jobs:
  udpate-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Update dependencies and actions
        run: pnpm run update
      - name: Update dependency overrides
        run: pnpm run maintain
      - name: Update lockfile
        run: pnpm install --ignore-scripts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PR_CREATE_TOKEN }}
          commit-message: Update dependencies
          title: "[Codependence] update dependencies"
          body: |
            ## Dependency updates
            Auto-generated by [codependence][1] using [create-pull-request][2]
            [1]: https://github.com/yowainwright/yowainwright.github.io
            [2]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          labels: codependencies
